# Generated by Django 4.1.3 on 2022-11-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_villan'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='villans',
            field=models.ManyToManyField(to='main_app.villan'),
        ),
    ]
